// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrj_sf575nn_ToJFHDwRMNtzv1Aw8XenQ',
    appId: '1:316580441902:web:f4aa31b6baa84f096554bf',
    messagingSenderId: '316580441902',
    projectId: 'fitbit-project-4a220',
    authDomain: 'fitbit-project-4a220.firebaseapp.com',
    storageBucket: 'fitbit-project-4a220.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByRzCPKrtr7UJaoeXskhMCjQxod8ES3j0',
    appId: '1:316580441902:android:62b13ae3ad172b366554bf',
    messagingSenderId: '316580441902',
    projectId: 'fitbit-project-4a220',
    storageBucket: 'fitbit-project-4a220.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUtCG7vBVseGyBz6UQN1pGzHRXF2jYpjA',
    appId: '1:316580441902:ios:14c925c6e27a68ec6554bf',
    messagingSenderId: '316580441902',
    projectId: 'fitbit-project-4a220',
    storageBucket: 'fitbit-project-4a220.firebasestorage.app',
    iosClientId: '316580441902-hjrtrubnrlejv3naqcccpplnlvt3bc40.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUtCG7vBVseGyBz6UQN1pGzHRXF2jYpjA',
    appId: '1:316580441902:ios:14c925c6e27a68ec6554bf',
    messagingSenderId: '316580441902',
    projectId: 'fitbit-project-4a220',
    storageBucket: 'fitbit-project-4a220.firebasestorage.app',
    iosClientId: '316580441902-hjrtrubnrlejv3naqcccpplnlvt3bc40.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrj_sf575nn_ToJFHDwRMNtzv1Aw8XenQ',
    appId: '1:316580441902:web:6a0f63ad038396906554bf',
    messagingSenderId: '316580441902',
    projectId: 'fitbit-project-4a220',
    authDomain: 'fitbit-project-4a220.firebaseapp.com',
    storageBucket: 'fitbit-project-4a220.firebasestorage.app',
  );
}
