// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnSef-Y3maaxMMOjae8HBEyhiIai3rGeA',
    appId: '1:594020358294:web:545a4c604d8a74b1638ab7',
    messagingSenderId: '594020358294',
    projectId: 'pulseai-501016',
    authDomain: 'pulseai-501016.firebaseapp.com',
    storageBucket: 'pulseai-501016.firebasestorage.app',
    measurementId: 'G-K6JDK5RQQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwzsPJnN3d2P_b-2s-Z18nrcMXbCnwYPs',
    appId: '1:594020358294:android:588392273b545f1d638ab7',
    messagingSenderId: '594020358294',
    projectId: 'pulseai-501016',
    storageBucket: 'pulseai-501016.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU4six5ANYXPUILSx2ZwQouDM9-n88paw',
    appId: '1:594020358294:ios:91f91f03af98512b638ab7',
    messagingSenderId: '594020358294',
    projectId: 'pulseai-501016',
    storageBucket: 'pulseai-501016.firebasestorage.app',
    androidClientId: '594020358294-0ivdd3nabbjafeqmd58vfre8ugdl93g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU4six5ANYXPUILSx2ZwQouDM9-n88paw',
    appId: '1:594020358294:ios:91f91f03af98512b638ab7',
    messagingSenderId: '594020358294',
    projectId: 'pulseai-501016',
    storageBucket: 'pulseai-501016.firebasestorage.app',
    androidClientId: '594020358294-0ivdd3nabbjafeqmd58vfre8ugdl93g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnSef-Y3maaxMMOjae8HBEyhiIai3rGeA',
    appId: '1:594020358294:web:f9511ca1b426efa9638ab7',
    messagingSenderId: '594020358294',
    projectId: 'pulseai-501016',
    authDomain: 'pulseai-501016.firebaseapp.com',
    storageBucket: 'pulseai-501016.firebasestorage.app',
    measurementId: 'G-E9LTFFNZHQ',
  );
}
